version: '3'

services:
  ## Postgres
  postgresql:
    image: 'char0n/postgresql-czech-fulltext'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=database
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
    ports:
      - '127.0.0.1:5432:5432'

  ## Redis
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    command: redis-server --loglevel warning --requirepass 6DRFzO5C9ZTpqJIXRxrsUb2XvayBnwT6
    volumes: 
      - redis:/data
    ports:
      - '6379:6379'

  ## Backend
  backend:
    build: backend
    container_name: ltp-backend
    volumes:
      - ./backend:/backend
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,webapp,10.0.0.16
      - DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost:8080
      - DJANGO_MEDIA_URL=http://localhost:8080/backend/media/
      - DJANGO_STATIC_URL=http://localhost:8080/backend/static/
      - DJANGO_DB_NAME=database
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=postgres
      - DJANGO_DB_HOST=postgresql
      - DJANGO_DB_PORT=5432
      - DJANGO_REDIS_LOCATION=redis://redis:6379/1
      - REDIS_PASSWORD=6DRFzO5C9ZTpqJIXRxrsUb2XvayBnwT6

  ## Frontend
  frontend:
    build: frontend
    container_name: ltp-frontend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
      - redis
    environment:
      - NODE_ENV=development

  ## NGINX
  edge:
    image: bitnami/nginx:latest
    container_name: ltp-edge
    ports:
      - '8080:8080'
    volumes:
      - ./edge/ltp.conf:/opt/bitnami/nginx/conf/server_blocks/ltp.conf:ro
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/static
    depends_on:
      - frontend
      - backend  

volumes:
  node_modules:
    driver: local
  postgresql_data:
    driver: local
  postgresql_initdb:
    driver: local
  postgresql_pre_initdb:
    driver: local
  redis:
    driver: local