name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2376:2376

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker Compose stack
      run: docker-compose -f docker-compose.yml build

    - name: Run entrypoint manually
      run: |
        docker-compose -f docker-compose.yml run backend /bin/sh -c "chmod +x /backend/entrypoint.sh; cat /backend/entrypoint.sh; /backend/entrypoint.sh"

    - name: Run tests
      run: |
        docker-compose -f docker-compose.yml up -d postgresql redis
        docker-compose -f docker-compose.yml run backend ./manage.py test
        docker-compose -f docker-compose.yml down

    - name: Push the Docker images
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        docker-compose -f docker-compose.yml push

